[package]
name = "cpu-meter"
version = "0.1.0"
edition = "2021"

[dependencies]
chaos-framework = "0.1.2"
sysinfo = "0.31.2"
tokio = { version = "1.39.2", features = ["full", "macros", "rt-multi-thread", "time"] }
